### ISSUE TITLE
Holes (again)

### ISSUE THREAD

**Issue by lgpmichael2** [velipso/polybooljs#30]
I've spent a while trying to modify the code to try and change it to add information about whether a poly is an inner bound, ie a hole. So for example:

{"regions":[
                  [[250,250],[250,150],[150,150],[150,250]],
                  [[300,300],[300,100],[100,100],[100,300]]],
                 "inverted":false}
                 
A basic square in a square, where the inner is the hole boundary.

I can calculate this myself using the data, find out how many polys a point is inside, but it struck me that, somewhere in your calculations, you HAVE this information, and it will be a LOT more efficient to just use what's already pre-calculated. So I've been trying to modify it so that the return looks like

{"regions":[
                  [[250,250],[250,150],[150,150],[150,250]],
                  [[300,300],[300,100],[100,100],[100,300]]],
                 "inverted":false,
                 "metadata":[{"innerbound": true},
                                     {"innerbound": false}]
}

Where the metadata is in the same order as the regions. I suppose making the polys each a class, even possibly with a hierarchy could be done, but this seemed to be least invasive, and backwards compatible.

I've watched your segments tutorial and it makes sense, but when it comes to modifying the code for this, I just can't wrap my head around the segmentchainer to do this. Any suggestions?

**Comment by velipso** [comment]
I can't think of a way to calculate the holes during intersection processing, though it might be possible.

However, it might interest you to check out [`lib/geojson.js`](https://github.com/velipso/polybooljs/blob/master/lib/geojson.js) in the library -- I had to solve the same problem (finding holes), and came up with an algorithm that figured out the hierarchy of region holes.

Now I don't know if my algorithm works in all cases, but it makes sense to me 😅 .

Also, instead of writing something yourself, you could just _use_ `polygonToGeoJSON(...)`, and extract out the holes using the winding of the polygon.

**Comment by lgpmichael2** [comment]
Thanks for the response. Yeah I'd looked at the conversion, and was hoping there was a way to do it without. The issue I have is that the program I'm writing is quite performance intensive, so I was looking for ways to speed it up. Your system you use on geojson is pretty similar to the one I am already using to work it out. It's not slow, but, faster is always better.

Oh well, was worth a try. Thanks very much for this library, it's been a huge help to me!
